export const REQUEST_USER_LANDMARKS = 'REQUEST_USER_LANDMARKS';
export const REQUEST_USER_LANDMARKS_FAILED = 'REQUEST_USER_LANDMARKS_FAILED';
export const RECEIVED_USER_LANDMARKS = 'RECEIVED_USER_LANDMARKS';