export const GOOGLE_MAP_LOADING = 'GOOGLE_MAP_LOADING';
export const GOOGLE_MAP_LOADING_FAILED = 'GOOGLE_MAP_LOADING_FAILED';
export const GOOGLE_MAP_LOADING_SUCCESS = 'GOOGLE_MAP_LOADING_SUCCESS';
export const MARK_USER_CURRENT_LOCATION = 'MARK_USER_CURRENT_LOCATION';